import Anthropic from '@anthropic-ai/sdk';
import { env } from '../config/env';
import { prisma } from '../db/client';
import { QueryBuilderService } from './QueryBuilderService';
import { ActivityService } from './ActivityService';

const anthropic = new Anthropic({
  apiKey: env.ANTHROPIC_API_KEY || 'sk-test',
});

export class AiService {
  static async processNlq(orgId: string, datasetId: string, userId: string, question: string) {
    const dataset = await prisma.dataset.findFirst({
      where: { id: datasetId, organization_id: orgId },
    });

    if (!dataset) throw new Error('Dataset not found');

    const schemaStr = JSON.stringify(dataset.schema_json);
    
    // Simulate prompt to Anthropic to generate SQL/Query Config based on natural language
    const prompt = `Given the following dataset schema:\n${schemaStr}\n\nGenerate a data query configuration to answer the question: "${question}". Respond with ONLY valid JSON representing the query config.`;

    let queryConfig: any = {};
    let explanation = "Generated by AI";

    if (env.ANTHROPIC_API_KEY) {
      try {
        const response = await anthropic.messages.create({
          model: 'claude-3-5-sonnet-20241022',
          max_tokens: 1024,
          system: "You are a data analyst assistant. Translate user questions into structured query JSON.",
          messages: [{ role: 'user', content: prompt }],
        });
        
        // Extract JSON from response (naive implementation)
        const content = response.content[0];
        if (content && 'text' in content) {
          const jsonMatch = content.text.match(/\{[\s\S]*\}/);
          if (jsonMatch) {
            queryConfig = JSON.parse(jsonMatch[0]);
          }
        }
      } catch (err) {
        console.error('Anthropic API error:', err);
        // Fallback or handle error
      }
    } else {
      // Dummy response for development without API key
      queryConfig = { filter: {}, groupBy: "category" };
    }

    // Execute generated query
    const results = await QueryBuilderService.executeQuery(orgId, datasetId, queryConfig);

    await ActivityService.log({
      organizationId: orgId,
      userId,
      action: 'NLQ_QUERY',
      entityType: 'dataset',
      entityId: datasetId,
      metadata: { question },
    });

    return { sql: queryConfig, explanation, results };
  }

  static async generateInsights(orgId: string, datasetId: string) {
    // Simulated insights generation job
    const insight = await prisma.aiInsight.create({
      data: {
        organization_id: orgId,
        project_id: 'default', // should map properly in real app
        type: 'summary',
        title: 'Monthly Data Summary',
        description: 'AI generated summary of the recent data trends indicating a 15% increase in primary metrics.',
        confidence_score: 0.85,
      }
    });
    return insight;
  }
}
